import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";
import { parseWorkflow } from "../src/definition";

type ChoiceQuestion = { question: string; options: { value: string; label: string }[] };
type AnswerDraft = { choice: string; text: string };
const { parseChoiceQuestion, resolveAnswer } = require("../ui/assets/human-input.js") as {
  parseChoiceQuestion(source: unknown): ChoiceQuestion | null;
  resolveAnswer(parsed: ChoiceQuestion | null, draft: AnswerDraft): string;
};

const footer = "Reply A, B, C, or your own answer.";
const question = `Where should we start? A) Web; B) Mobile; C) Desktop. ${footer}`;

test("renders all four questions generated by the two-agent example as exact choices", async () => {
  const sourcePath = "workflows/two-agent-multiple-choice.yaml";
  const definition = parseWorkflow(await readFile(sourcePath, "utf8"), sourcePath);
  const fixtures = [
    ["product_interviewer", "audience_question", "Product agent / Audience: Who should the first task-tracker release serve?", [
      "Individuals, with a private personal workspace",
      "Families, with shared household tasks",
      "Small teams, with owners and shared project visibility.",
    ]],
    ["product_interviewer", "priority_question", "Product agent / Priority: Which workflow should lead the first release?", [
      "Daily planning, focused on today's tasks",
      "Shared projects, focused on assignments and milestones",
      "Incoming requests, focused on triage and handoffs.",
    ]],
    ["technical_interviewer", "platform_question", "Technical agent / Platform: Where should the first release run?", [
      "Responsive web, accessible by a browser link",
      "Native mobile, focused on phone interactions",
      "Desktop, focused on keyboard-driven work.",
    ]],
    ["technical_interviewer", "storage_question", "Technical agent / Storage: How should task data be stored?", [
      "Device only, without automatic sharing or sync",
      "Hosted cloud sync, with a managed shared backend",
      "Self-hosted server, with deployment and backups owned by the operator.",
    ]],
  ] as const;
  for (const [nodeId, field, expectedQuestion, labels] of fixtures) {
    const output = definition.nodes.find((node) => node.id === nodeId)?.demo_output as Record<string, unknown>;
    assert.deepEqual(parseChoiceQuestion(output[field]), {
      question: expectedQuestion,
      options: labels.map((label, index) => ({ value: String.fromCharCode(65 + index), label })),
    }, field);
  }
});

test("preserves semicolons and line breaks within option descriptions", () => {
  assert.deepEqual(parseChoiceQuestion(`What works?\nA) Web; share a link;\nB) Mobile, with\nnotifications;\nC) Desktop; keyboard first.\n${footer}`), {
    question: "What works?",
    options: [
      { value: "A", label: "Web; share a link" },
      { value: "B", label: "Mobile, with\nnotifications" },
      { value: "C", label: "Desktop; keyboard first." },
    ],
  });
});

test("keeps ordinary and incomplete questions in the free-text form", () => {
  for (const source of [
    undefined, null, 42, {}, "", "What would you like to build?",
    "Explain how A) planning and B) delivery differ.",
    "Where? A) Web; B) Mobile; C) Desktop.",
    `Where? A) Web; C) Desktop. ${footer}`,
    `Where? A) Web; B) Mobile; C) Desktop. ${footer} More instructions follow.`,
  ]) assert.equal(parseChoiceQuestion(source), null, JSON.stringify(source));
});

test("rejects reordered, duplicate, ambiguous, and empty option labels", () => {
  for (const source of [
    `Where? A) Web; C) Desktop; B) Mobile. ${footer}`,
    `Where? A) Web; B) Mobile; B) Desktop. ${footer}`,
    `Where? A) Web; B) Mobile; C) Desktop. Reply A, C, B, or your own answer.`,
    `Where? A) Web; B) Mobile; C) Desktop. Reply A, B, B, or your own answer.`,
    `Where? A) Web B) Mobile; B) Phone; C) Desktop. ${footer}`,
    `Where? A) Web; B) ; C) Desktop. ${footer}`,
    `Where? A) Web; B) Mobile; C)   ${footer}`,
  ]) assert.equal(parseChoiceQuestion(source), null, source);
});

test("submits the selected letter without silently using an unselected custom draft", () => {
  const parsed = parseChoiceQuestion(question);
  assert.ok(parsed);
  for (const choice of ["A", "B", "C"]) {
    assert.equal(resolveAnswer(parsed, { choice, text: "Different custom answer" }), choice);
  }
  for (const choice of ["", "D", "b", " B "]) {
    assert.equal(resolveAnswer(parsed, { choice, text: "Unselected custom answer" }), "");
  }
});

test("custom answers retain their content while rejecting whitespace-only submissions", () => {
  const parsed = parseChoiceQuestion(question);
  assert.ok(parsed);
  assert.equal(resolveAnswer(parsed, { choice: "__custom__", text: "  Web and mobile;\nkeep both options.  " }), "Web and mobile;\nkeep both options.");
  assert.equal(resolveAnswer(parsed, { choice: "__custom__", text: " \n\t " }), "");
});

test("ordinary questions resolve trimmed text regardless of a stale choice value", () => {
  assert.equal(resolveAnswer(null, { choice: "B", text: "  A custom response\nwith context.  " }), "A custom response\nwith context.");
  assert.equal(resolveAnswer(null, { choice: "", text: "\n " }), "");
});
